### ISSUE TITLE
My guess about issue41210

### ISSUE THREAD

**Issue by ghost** [miurahr/bcj-cffi#1]
I read this reply in https://bugs.python.org/issue41210

> 3. it returns 4 bytes less size than expected.
> 
> for 3, it is because return value  of BCJ is defined such as
> ```c
> 	size -= 4;
> 	for (i = 0; i < size; ++i) {...}
>         return i;
> ```
> and  variable i sometimes increment 4 bytes when target sequence is found and processed.
> It may be natural that a size value returned from BCJ filter is often 4 bytes smaller than actual.

The return value of `x86_code()` function is "filtered length", `x86_code()` always return (full length - 4).

In file `/xz-embedded-20130513/linux/lib/xz/xz_dec_bcj.c`, Line 62, there is a description.
I guess it is related to the 4 bytes here.
```
    /*
     * Buffer to hold a mix of filtered and unfiltered data. This
     * needs to be big enough to hold Alignment + 2 * Look-ahead:
     *
     * Type         Alignment   Look-ahead
     * x86              1           4
     * PowerPC          4           0
     * IA-64           16           0
     * ARM              4           0
     * ARM-Thumb        2           2
     * SPARC            4           0
     */
```

In liblzma, [`src/liblzma/simple/simple_coder.c#l192`](https://git.tukaani.org/?p=xz.git;a=blob;f=src/liblzma/simple/simple_coder.c#l192)
```c
    // Everything is considered to be filtered if coder->buffer[]
    // contains the last bytes of the data.
    if (coder->end_was_reached)
        coder->filtered = coder->size;

    // Flush as much as possible.
    lzma_bufcpy(coder->buffer, &coder->pos, coder->filtered,
                out, out_pos, out_size);
```
I guess `LZMA1` doesn't have a suitable `end_was_reached` marker, so the last bytes were not copied to the output buffer.
When I have time, I will try to debug it to see if this is right.

**Comment by ghost** [comment]
I read Lasse Collin's reply:
https://www.mail-archive.com/xz-devel@tukaani.org/msg00373.html

It seem the guess is right, then I won't debug it.

> So even if the liblzma was improved to handle the lack of end marker
> in a better way, you still couldn't decompress all .7z files. For .7z, 
> LZMA SDK is the way to go.
>
> Using liblzma to decode .7z works in these cases:
>
>  - LZMA1 using a fake 13-byte header with lzma_alone_decoder():
>
>        1 byte   LZMA properties byte that encodes lc/lp/pb
>        4 bytes  dictionary size as little endian uint32_t
>        8 bytes  uncompressed size as little endian uint64_t;
>                 UINT64_MAX means unknown and then (and only then)
>                 EOPM must be present
>
>  - LZMA2, possibly together with a BCJ or Delta filter, with
>    lzma_raw_decoder() since LZMA2 always includes the end marker.

If `py7zr` implements a `x86 BCJ filter` by itself, then it can process `x86 BCJ filter` + `LZMA1` data.

You said:
> 7-zip container format has size database, then library can know output is enough or not.

You can write a `x86 BCJ filter` with Python, use it to process decompressed `LZMA1` data without end marker.
Implement a `x86 BCJ filter` with Python is very easy, [here](https://github.com/animalize/misc/blob/master/x86.py) is a rough implementation.

But for long future, I would suggest writing a LZMA SDK layer, and let `py7zr` use it.

**Comment by miurahr** [comment]
Thank @animalize  for your suggestion and  implementation!
Now I made PR at https://github.com/miurahr/py7zr/pull/198 which introduce alternative BCJ filter written by Python.

**Comment by ghost** [comment]
Maybe there should be a ARM-Thumb alternative filter as well, it would be nice to test all BCJ filters.
Don't know if it worthy to support BCJ2 in this way.

If add 200~300 lines code to `_lzmamodule.c`, we can fix this particular combination(LZMA1+x86), but it will make the code very complex.

**Comment by ghost** [comment]
Sorry, miss clicked.

**Comment by miurahr** [comment]
It would be not worthy to add code to `_lzmamodule.c` , because LZMA1 is legacy method, my recommendation `XZ` use LZMA2, it only used it in older 7-zip archives. Current p7zip and 7-zip on windows use a LZMA2+BCJ as default.

I'd like to make bcj-cffi project archvied because it is just a test project.

**Comment by ghost** [comment]
OK, close this issue.
