### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [miurahr/bcj-cffi#4]
**Is your feature request related to a problem? Please describe.**
Working towards making `py7zr` available on conda.

**Describe the solution you'd like**
Add a conda recipe.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by miurahr** [comment]
Thanks for your effort! https://github.com/conda-forge/staged-recipes/pull/15513

**Comment by sarthakpati** [comment]
Closing this.
